server:
    port: 8201
spring:
    profiles: dev
    application:
        name: stucloud-config-client
eureka:
    client:
        service-url:
            defaultZone: http://depteureka7001.com:7001/eureka/
---
server:
    port: 8202
spring:
    profiles: test
    application:
        name: stucloud-config-client
eureka:
    client:
        service-url:
            defaultZone: http://depteureka7001.com:7001/eureka/
